apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 18-grout-iface-config
spec:
  config:
    ignition:
      version: 3.5.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Configure netdev %i for grout usage
            After=network-online.target
            Before=grout-container.service
            Wants=network-online.target

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/bin/grout-iface-config %i

            [Install]
            WantedBy=multi-user.target
          name: grout-bind@.service
  files:
        - path: /bin/grout-iface-config
          mode: 0755
          overwrite: true
          contents:
            inline: |
                #!/bin/bash
                # driverctl is not available, bind manually to vfio-pci if the device
                # is not a mellanox NIC.

                vfio_bind() {
                    local netdev=$1
                    local driver=$2
                    local pci_addr=$3

                    /sbin/modprobe vfio-pci
                    echo "vfio-pci" > /sys/bus/pci/devices/$pci_addr/driver_override
                    echo $pci_addr > /sys/bus/pci/drivers/$driver/unbind || true
                    echo $pci_addr > /sys/bus/pci/drivers/vfio-pci/bind
                    echo "Bound $netdev with addr $pci_addr to vfio-pci"
                }

                mlx_bind() {
                    local netdev=$1
                    local driver=$2
                    local pci_addr=$3
                    if [ ! -e /var/run/netns/hbn-grout ] ; then
                        ip netns add hbn-grout
                    fi
                    ip link set $netdev netns hbn-grout
                    echo "Moved $netdev to network namespace 'hbn-grout'"
                }

                driver=$(ethtool -i $1 | awk '/driver: (.*)/ {print $2}')
                pci_addr=$(ethtool -i $1 | awk '/bus-info: (.*)/ {print $2}')

                if [[ -z "$1" ]] ; then echo "No argument."; exit -1 ; fi
                if [[ -z "$driver"]]; then echo "Driver not found for netdev $1." ; exit -1 ; fi
                if [[ -z "$pci_addr"]]; then echo "pci address not found for netdev $1." ; exit -1 ; fi

                if [[ "$driver" =~ "mlx5" ]] ; then
                    mlx_bind $1 $driver $pci_addr
                else
                    vfio_bind $1 $driver $pci_addr
                fi
