---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grout-telemetry-exporter
  namespace: grout-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-grout-monitoring-view
  namespace: grout-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grout-telemetry-exporter
  namespace: grout-monitoring
  labels:
    app: grout-telemetry
spec:
  selector:
    matchLabels:
      app: grout-telemetry
  template:
    metadata:
      labels:
        app: grout-telemetry
    spec:
      serviceAccountName: grout-telemetry-exporter
      hostNetwork: true
      containers:
      - name: socat
        image: alpine/socat:latest
        args:
          - TCP4-LISTEN:9877,fork,reuseaddr
          - TCP4:127.0.0.1:9876
        ports:
        - containerPort: 9877
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: grout-telemetry-service
  namespace: grout-monitoring
  labels:
    app: grout-telemetry
spec:
  clusterIP: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: grout-telemetry
  ports:
  - name: metrics
    port: 9877
    protocol: TCP
    targetPort: 9877
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grout-telemetry-monitor
  namespace: grout-monitoring
  labels:
    app: grout-telemetry
spec:
  selector:
    matchLabels:
      app: grout-telemetry
  endpoints:
  - port: metrics
    interval: 30s
    path: /
    scheme: http
