---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: eno49-network
  namespace: openshift-sriov-network-operator
spec:
  resourceName: eno49netdevice
  networkNamespace: default
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.42.0/24",
      "range_start": "192.168.42.10",
      "range_end": "192.168.42.254",
      "gateway": "192.168.42.1",
      "routes": [{
        "dst": "0.0.0.0/0",
        "gw": "192.168.42.1"
      }]
    }
  vlan: 42
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: eno50-network
  namespace: openshift-sriov-network-operator
spec:
  resourceName: eno50netdevice
  networkNamespace: default
  ipam: '{}'
  vlan: 211
